/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElConfigProvider: typeof import("element-plus/es")["ElConfigProvider"];
    ElForm: typeof import("element-plus/es")["ElForm"];
    ElFormItem: typeof import("element-plus/es")["ElFormItem"];
    ElInput: typeof import("element-plus/es")["ElInput"];
    HelloWorld: typeof import("./src/components/HelloWorld.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
  }
}
